version: '3.7'
services:
  app:
    container_name: stomat
    image: gradle:5.3.1-jdk11
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - 8080
    command: gradle test -Dspring.profiles.active=docker
    depends_on:
      - postgres
    networks:
      - stomat-network-test

  postgres:
    container_name: stomat-postgres
    image: postgres:9.6
    user: postgres
    environment:
      POSTGRES_USER: stomatuserdb
      POSTGRES_DB: stomatdb
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - ./data/docker/volumes/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - stomat-network-test
    secrets:
      - postgres_password

networks:
  stomat-network-test:
    driver: bridge

secrets:
  postgres_password:
    file: ./external-config/docker/postgres/secrets/postgres_password

